### ISSUE TITLE
Use ueberzug for preview rendering

### ISSUE THREAD

**Issue by sarmong** [adelarsq/image_preview.nvim#4]
[ueberzug](https://github.com/seebye/ueberzug) works in all terminals, so there will be no need to support different renderers

**Comment by adelarsq** [comment]
@sarmong Thanks for the report. Sorry for the delay

I was thinking about that but since ueberzug is not maintained anymore I decide to drop this dependency.

For rendering purposes I have plans to create my own tool when possible. That's is why I will close this issue for now. I will revisit this is issue in the couple of months.

**Comment by FelipeLema** [comment]
there's ueberzugpp now, so we may want to revisit this feature
